module.exports = {
	tailwindConfig: './tailwind.config.js',
	arrowParens: 'avoid',
	bracketSameLine: true,
	bracketSpacing: true,
	endOfLine: 'lf',
	htmlWhitespaceSensitivity: 'css',
	jsxSingleQuote: true,
	printWidth: 80,
	proseWrap: 'preserve',
	quoteProps: 'consistent',
	requirePragma: false,
	semi: true,
	singleAttributePerLine: false,
	singleQuote: true,
	tabWidth: 3,
	trailingComma: 'es5',
	useTabs: true,
};
